[features]
seeds = false
[programs.localnet]
my_solana_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
my_solana_program = "2kx16UybH5HZkX1AimamBqqJ6mYstTgqR2jmVinV3GJS"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"
#cluster = "http://10.0.0.50:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
